spring:
    jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
        show-sql: true
    datasource:
        url: jdbc:postgresql://localhost:5432/OnlineBookReader
        username: postgres
        password: 1
        driver-class-name: org.postgresql.Driver
    application:
        name: OnlineBookReader
